/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package org.net.perorin.bastet.app

import java.awt.SplashScreen

import org.net.perorin.bastet.window.Window

class App {
    static void main(String[] args) {

		// ラベルの文字を強制アンチエイリアシングする
		System.setProperty("prism.lcdtext", "false");
        Window.launch(Window.class, args)

		SplashScreen splash = SplashScreen.getSplashScreen();
		if(splash != null) {
			splash.close();
		}
    }
}
